- name: remove nginx 
  command:
    "rpm -e nginx-1.15.9-1.el7_4.x86_64"
  ignore_errors: yes   
- name: install nginx 
  yum:
    name: "nginx-1.12.2-2.el7.x86_64"
    state: present

- name: remove nginx vhost default.conf
  command:
    "mv /etc/nginx/conf.d/default.conf /tmp"
  ignore_errors: yes
- name: install nginx configuration
  template:
    src:  nginx.conf.j2
    dest: /etc/nginx/nginx.conf 
  register: nginx_conf_1

- name: install vhosts conf
  template:
    src: "s1_service.conf.j2"
    dest: "/etc/nginx/conf.d/s1_service.conf"
  with_fileglob:
    - "{{role_path}}/templates/s1_service.conf.j2"
  register: nginx_conf_2
  ignore_errors: yes

- name: restart nginx 
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: nginx_conf_1 is changed or nginx_conf_2 is changed


- name: add firewalld rules
  firewalld:
    zone: public
    port: 80/tcp
    permanent: true
    state: enabled

- name: reload firewalld 
  shell: firewall-cmd --reload
